# Generated by Django 5.1.7 on 2025-09-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscodedVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_video", models.FileField(upload_to="uploads/")),
                (
                    "codec",
                    models.CharField(
                        choices=[
                            ("h264", "H.264"),
                            ("h265", "H.265"),
                            ("av1", "AV1"),
                            ("vp9", "VP9"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "profile",
                    models.CharField(
                        choices=[
                            ("baseline", "Baseline"),
                            ("main", "Main"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("resolutions", models.JSONField()),
                ("output_folder", models.CharField(max_length=255)),
                ("transcoding_time", models.FloatField(blank=True, null=True)),
                ("bandwidth", models.FloatField(blank=True, null=True)),
                ("storage_used", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
