# Generated by Django 5.1.7 on 2025-09-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_transcodedvideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcodedvideo",
            name="size_per_resolution",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
