# Generated by Django 5.1.7 on 2025-09-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_transcodedvideo_size_per_resolution"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcodedvideo",
            name="source_size",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
